# Generated by Django 5.1.1 on 2024-09-17 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appreciation', '0002_post_to'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
    ]
